package svgimport;

class SvgAttributes
{
	public static var presentation(default, null) =
	[
		"alignment-baseline",
		"baseline-shift",
		"clip",
		"clip-path",
		"clip-rule",
		"color",
		"color-interpolation",
		"color-interpolation-filters",
		"color-profile",
		"color-rendering",
		"cursor",
		"direction",
		"display",
		"dominant-baseline",
		"enable-background",
		"fill",
		"fill-opacity",
		"fill-rule",
		"filter",
		"flood-color",
		"flood-opacity",
		"font-family",
		"font-size",
		"font-size-adjust",
		"font-stretch",
		"font-style",
		"font-variant",
		"font-weight",
		"glyph-orientation-horizontal",
		"glyph-orientation-vertical",
		"image-rendering",
		"kerning",
		"letter-spacing",
		"lighting-color",
		"marker-end",
		"marker-mid",
		"marker-start",
		"mask",
		"opacity",
		"overflow",
		"pointer-events",
		"shape-rendering",
		"stop-color",
		"stop-opacity",
		"stroke",
		"stroke-dasharray",
		"stroke-dashoffset",
		"stroke-linecap",
		"stroke-linejoin",
		"stroke-miterlimit",
		"stroke-opacity",
		"stroke-width",
		"text-anchor",
		"text-decoration",
		"text-rendering",
		"unicode-bidi",
		"visibility",
		"word-spacing",
		"writing-mode"
	];
	
	public static var presentationNoInherit =
	[
		"clip-path",
		"filter"
	];
}